apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-admin
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: nextcloud-admin
    creationPolicy: Owner
  data:
    - secretKey: nextcloud-username
      remoteRef:
        key: apps/productivity/nextcloud-admin
        property: nextcloud-username
    - secretKey: nextcloud-password
      remoteRef:
        key: apps/productivity/nextcloud-admin
        property: nextcloud-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-db
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: nextcloud-db
    creationPolicy: Owner
  data:
    - secretKey: db-username
      remoteRef:
        key: apps/productivity/nextcloud-db
        property: db-username
    - secretKey: password
      remoteRef:
        key: apps/productivity/nextcloud-db
        property: password
    - secretKey: postgres-password
      remoteRef:
        key: apps/productivity/nextcloud-db
        property: postgres-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-redis
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: nextcloud-redis
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: apps/productivity/nextcloud-redis
        property: redis-password
