apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-appdata
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  storageClassName: ceph-block
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-postgresql-data
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  storageClassName: ceph-block
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-redis-data
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  storageClassName: ceph-block
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 2Gi
