apiVersion: batch/v1
kind: Job
metadata:
  name: seed-nextcloud-appdata
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: seed
          image: alpine:3.20
          command: ["/bin/sh", "-lc"]
          args:
            - |
              set -e
              apk add --no-cache rsync
              src="/nas/nextcloud/nextcloud-appdata"
              dst="/appdata"
              if [ ! -d "$src" ]; then
                echo "missing source $src"; exit 1
              fi
              mkdir -p "$dst"
              rsync -aHAX --numeric-ids "$src"/ "$dst"/
          volumeMounts:
            - name: appdata
              mountPath: /appdata
            - name: nas-migrate
              mountPath: /nas
              readOnly: true
          resources:
            requests: { cpu: "50m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: nextcloud-appdata
        - name: nas-migrate
          hostPath:
            path: /NAS/Longhorn
            type: Directory
