apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-widget-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: homepage-widget-secrets
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_NEXTCLOUD_USERNAME
      remoteRef:
        key: apps/productivity/nextcloud-admin
        property: nextcloud-username
    - secretKey: HOMEPAGE_VAR_NEXTCLOUD_PASSWORD
      remoteRef:
        key: apps/productivity/nextcloud-admin
        property: nextcloud-password
    - secretKey: HOMEPAGE_VAR_QBIT_USERNAME
      remoteRef:
        key: apps/media/qb-webui-creds
        property: username
    - secretKey: HOMEPAGE_VAR_QBIT_PASSWORD
      remoteRef:
        key: apps/media/qb-webui-creds
        property: password
    - secretKey: HOMEPAGE_VAR_QBIT_LTS_USERNAME
      remoteRef:
        key: apps/media/qb-lts-webui-creds
        property: username
    - secretKey: HOMEPAGE_VAR_QBIT_LTS_PASSWORD
      remoteRef:
        key: apps/media/qb-lts-webui-creds
        property: password
    - secretKey: HOMEPAGE_VAR_QBIT_LTS2_USERNAME
      remoteRef:
        key: apps/media/qb-lts2-webui-creds
        property: username
    - secretKey: HOMEPAGE_VAR_QBIT_LTS2_PASSWORD
      remoteRef:
        key: apps/media/qb-lts2-webui-creds
        property: password
    - secretKey: HOMEPAGE_VAR_JELLYFIN_KEY
      remoteRef:
        key: apps/productivity/homepage-media-widgets
        property: JELLYFIN_KEY
    - secretKey: HOMEPAGE_VAR_IMMICH_KEY
      remoteRef:
        key: apps/productivity/homepage-media-widgets
        property: IMMICH_KEY
    - secretKey: HOMEPAGE_VAR_JELLYSEERR_KEY
      remoteRef:
        key: apps/productivity/homepage-media-widgets
        property: JELLYSEERR_KEY
    - secretKey: HOMEPAGE_VAR_SONARR_KEY
      remoteRef:
        key: apps/productivity/homepage-media-widgets
        property: SONARR_KEY
    - secretKey: HOMEPAGE_VAR_RADARR_KEY
      remoteRef:
        key: apps/productivity/homepage-media-widgets
        property: RADARR_KEY
    - secretKey: HOMEPAGE_VAR_LIDARR_KEY
      remoteRef:
        key: apps/productivity/homepage-media-widgets
        property: LIDARR_KEY
    - secretKey: HOMEPAGE_VAR_PROWLARR_KEY
      remoteRef:
        key: apps/productivity/homepage-media-widgets
        property: PROWLARR_KEY
    - secretKey: HOMEPAGE_VAR_TRUENAS_KEY
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: TRUENAS_KEY
    - secretKey: HOMEPAGE_VAR_OPNSENSE_USERNAME
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: OPNSENSE_USERNAME
    - secretKey: HOMEPAGE_VAR_OPNSENSE_PASSWORD
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: OPNSENSE_PASSWORD
    - secretKey: HOMEPAGE_VAR_HEADSCALE_NODE_ID
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: HEADSCALE_NODE_ID
    - secretKey: HOMEPAGE_VAR_HEADSCALE_KEY
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: HEADSCALE_KEY
    - secretKey: HOMEPAGE_VAR_UNIFI_USERNAME
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: UNIFI_USERNAME
    - secretKey: HOMEPAGE_VAR_UNIFI_PASSWORD
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: UNIFI_PASSWORD
    - secretKey: HOMEPAGE_VAR_ARGOCD_KEY
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: ARGOCD_KEY
    - secretKey: HOMEPAGE_VAR_GLANCES_BALTHASAR_URL
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: GLANCES_BALTHASAR_URL
    - secretKey: HOMEPAGE_VAR_GLANCES_BALTHASAR_USERNAME
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: GLANCES_BALTHASAR_USERNAME
    - secretKey: HOMEPAGE_VAR_GLANCES_BALTHASAR_PASSWORD
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: GLANCES_BALTHASAR_PASSWORD
    - secretKey: HOMEPAGE_VAR_GLANCES_CASPER_URL
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: GLANCES_CASPER_URL
    - secretKey: HOMEPAGE_VAR_GLANCES_CASPER_USERNAME
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: GLANCES_CASPER_USERNAME
    - secretKey: HOMEPAGE_VAR_GLANCES_CASPER_PASSWORD
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: GLANCES_CASPER_PASSWORD
    - secretKey: HOMEPAGE_VAR_GLANCES_MELCHIOR_URL
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: GLANCES_MELCHIOR_URL
    - secretKey: HOMEPAGE_VAR_GLANCES_MELCHIOR_USERNAME
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: GLANCES_MELCHIOR_USERNAME
    - secretKey: HOMEPAGE_VAR_GLANCES_MELCHIOR_PASSWORD
      remoteRef:
        key: apps/productivity/homepage-infra-widgets
        property: GLANCES_MELCHIOR_PASSWORD
