apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-widget-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: homepage-widget-secrets
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_NEXTCLOUD_USERNAME
      remoteRef:
        key: apps/productivity/nextcloud-admin
        property: nextcloud-username
    - secretKey: HOMEPAGE_VAR_NEXTCLOUD_PASSWORD
      remoteRef:
        key: apps/productivity/nextcloud-admin
        property: nextcloud-password
    - secretKey: HOMEPAGE_VAR_QBIT_USERNAME
      remoteRef:
        key: apps/media/qb-webui-creds
        property: username
    - secretKey: HOMEPAGE_VAR_QBIT_PASSWORD
      remoteRef:
        key: apps/media/qb-webui-creds
        property: password
    - secretKey: HOMEPAGE_VAR_QBIT_LTS_USERNAME
      remoteRef:
        key: apps/media/qb-lts-webui-creds
        property: username
    - secretKey: HOMEPAGE_VAR_QBIT_LTS_PASSWORD
      remoteRef:
        key: apps/media/qb-lts-webui-creds
        property: password
    - secretKey: HOMEPAGE_VAR_QBIT_LTS2_USERNAME
      remoteRef:
        key: apps/media/qb-lts2-webui-creds
        property: username
    - secretKey: HOMEPAGE_VAR_QBIT_LTS2_PASSWORD
      remoteRef:
        key: apps/media/qb-lts2-webui-creds
        property: password
