apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama-static-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama-static-b
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama-swap
