apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: haproxy
spec:
  # Matches HAProxy Technologies Kubernetes Ingress Controller when Gateway API support is enabled.
  controllerName: haproxy.org/gateway-controller
