apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  storageClassName: ceph-block
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 128Mi
