apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unifi-db-credentials
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: unifi-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: MONGO_PASS
      remoteRef:
        key: apps/productivity/unifi-db-credentials
        property: MONGO_PASS
