apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  storageClassName: ceph-block
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-db
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  storageClassName: ceph-block
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 8Gi
