apiVersion: batch/v1
kind: Job
metadata:
  name: restore-unifi-db
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: restore
          image: mongo:6.0.11
          env:
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: unifi-db-credentials
                  key: MONGO_PASS
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              DUMP_DIR="/nas/unifi/mongodump"
              DUMP_FILE="$(ls -1 ${DUMP_DIR}/unifi-*.archive.gz 2>/dev/null | sort | tail -n1)"
              if [ -z "$DUMP_FILE" ]; then
                echo "no mongodump archive found in $DUMP_DIR"; exit 1
              fi
              for i in $(seq 1 60); do
                mongosh --host unifi-db --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1 && break
                sleep 5
              done
              mongosh --host unifi-db --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1 || {
                echo "mongo not ready"; exit 1; }
              mongorestore --drop --gzip --archive="$DUMP_FILE" \
                --host unifi-db \
                --username unifi --password "$MONGO_PASS" --authenticationDatabase unifi
          volumeMounts:
            - name: nas-migrate
              mountPath: /nas
              readOnly: true
      volumes:
        - name: nas-migrate
          hostPath:
            path: /NAS/Longhorn
            type: Directory
