# Linkerd Viz Helm values.
#
linkerdNamespace: service-mesh
defaultRegistry: harbor.rcrumana.xyz/mirror/linkerd
imagePullSecrets:
  - name: harbor-pull-creds

namespaceMetadata:
  image:
    registry: harbor.rcrumana.xyz/mirror/linkerd
    tag: v0.1.9

prometheus:
  enabled: false

prometheusUrl: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090

dashboard:
  enforcedHostRegexp: ""

# Prevent Helm from generating/churning self-signed TLS Secrets. These Secrets
# are created by cert-manager via `cluster/platform/service-mesh/linkerd/control-plane/identity/viz-tap.yaml`.
tap:
  externalSecret: true
  injectCaFrom: service-mesh/linkerd-webhook-ca

tapInjector:
  externalSecret: true
  injectCaFrom: service-mesh/linkerd-webhook-ca
