apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 8Gi
