apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: opnsense-https-1
  labels:
    kubernetes.io/service-name: opnsense-https
addressType: IPv4
ports:
  - name: https
    protocol: TCP
    port: 4443
endpoints:
  - addresses:
      - 192.168.1.1

