apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: librechat-meilisearch
  labels:
    app: librechat-meilisearch
spec:
  serviceName: librechat-meilisearch
  replicas: 1
  selector:
    matchLabels:
      app: librechat-meilisearch
  template:
    metadata:
      labels:
        app: librechat-meilisearch
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.13
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7700
          env:
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: librechat-secret
                  key: MEILI_MASTER_KEY
          resources:
            requests:
              cpu: "300m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: meilisearch-data
              mountPath: /meili_data
      volumes:
        - name: meilisearch-data
          persistentVolumeClaim:
            claimName: librechat-meilisearch-data
