apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librechat-meilisearch-data
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
