apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librechat-mongodb-data
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
