apiVersion: v1
kind: Service
metadata:
  name: librechat-mongodb
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  selector:
    app: librechat-mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
