apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: librechat-redis
  labels:
    app: librechat-redis
spec:
  serviceName: librechat-redis
  replicas: 1
  selector:
    matchLabels:
      app: librechat-redis
  template:
    metadata:
      labels:
        app: librechat-redis
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: redis
          image: redis:7.4-alpine
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - >-
              exec redis-server --appendonly yes --requirepass "$REDIS_PASSWORD"
          ports:
            - name: redis
              containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: librechat-secret
                  key: REDIS_PASSWORD
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: librechat-redis-data
