apiVersion: v1
kind: ServiceAccount
metadata:
  name: librechat
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: librechat-rag-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: librechat-meilisearch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: librechat-mongodb
