apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: v1
kind: Namespace
metadata:
  name: databases
---
apiVersion: v1
kind: Namespace
metadata:
  name: backup
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: networking
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
---
apiVersion: v1
kind: Namespace
metadata:
  name: scheduling
---
apiVersion: v1
kind: Namespace
metadata:
  name: service-mesh
  annotations:
    # Prevent Linkerd from injecting into its own control-plane namespace.
    linkerd.io/inject: disabled
  labels:
    # Linkerd CNI runs privileged and uses hostPath mounts.
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    linkerd.io/is-control-plane: "true"
    linkerd.io/control-plane-ns: service-mesh
    config.linkerd.io/admission-webhooks: disabled
