apiVersion: v1
kind: Endpoints
metadata:
  name: minio
subsets:
  - addresses:
      - ip: 192.168.1.10
    ports:
      - name: http
        port: 9002
        protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-api
subsets:
  - addresses:
      - ip: 192.168.1.10
    ports:
      - name: http
        port: 9000
        protocol: TCP
