apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: minio-api-manual
  labels:
    kubernetes.io/service-name: minio-api
    endpointslice.kubernetes.io/managed-by: argocd-manual
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 9000
endpoints:
  - addresses:
      - 192.168.1.10
    conditions:
      ready: true
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: minio-manual
  labels:
    kubernetes.io/service-name: minio
    endpointslice.kubernetes.io/managed-by: argocd-manual
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 9002
endpoints:
  - addresses:
      - 192.168.1.10
    conditions:
      ready: true
