apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-origin-default-cert
  namespace: ingress-haproxy
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cloudflare-origin-default-cert
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: apps/ingress-haproxy/cloudflare-origin-default-cert
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: apps/ingress-haproxy/cloudflare-origin-default-cert
        property: tls.key
