apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-reasoning-cache
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 130Gi
