apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-image-builder-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 200Gi
