apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-general-model-cache
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  storageClassName: ceph-block
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 100Gi
