apiVersion: batch/v1
kind: CronJob
metadata:
  name: vllm-image-builder
spec:
  schedule: "25 5 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          restartPolicy: Never
          enableServiceLinks: false
          containers:
            - name: build
              image: quay.io/buildah/stable:v1.39
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - /scripts/build-nightly.sh
              env:
                - name: GHCR_USER
                  valueFrom:
                    secretKeyRef:
                      name: vllm-shared-secret
                      key: GHCR_USER
                - name: GHCR_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: vllm-shared-secret
                      key: GHCR_TOKEN
                - name: TARGET_REPO
                  value: ghcr.io/rrumana/vllm-openai-rocm-gfx1150
                - name: TRACK_TAG
                  value: nightly-gfx1150
                - name: ROCM_ARCH
                  value: gfx1150
                - name: VLLM_REF
                  value: main
                - name: STORAGE_DRIVER
                  value: overlay
                - name: IMAGE_FORMAT
                  value: docker
                - name: HARD_RESET_STORAGE_ON_START
                  value: "1"
                - name: FORCE_BUILD
                  value: "0"
                - name: BUILDER_REVISION
                  value: "2026-02-19-4"
                - name: BUILDAH_ISOLATION
                  value: chroot
              securityContext:
                privileged: true
              resources:
                requests:
                  cpu: "4"
                  memory: "12Gi"
                limits:
                  cpu: "8"
                  memory: "24Gi"
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
                  readOnly: true
                - name: workspace
                  mountPath: /workspace
                - name: containers-storage
                  mountPath: /var/lib/containers
          volumes:
            - name: scripts
              configMap:
                name: vllm-image-builder-scripts
                defaultMode: 0555
            - name: workspace
              persistentVolumeClaim:
                claimName: vllm-image-builder-cache
            - name: containers-storage
              persistentVolumeClaim:
                claimName: vllm-image-builder-cache
