apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opensearch-admin-credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: opensearch-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: OPENSEARCH_USERNAME
      remoteRef:
        key: apps/search/opensearch-admin
        property: username
    - secretKey: OPENSEARCH_PASSWORD
      remoteRef:
        key: apps/search/opensearch-admin
        property: password
