# platform/gitops/argocd/apps/egress-qos-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: egress-qos
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://github.com/rrumana/k8s-homelab-2.git
    targetRevision: main
    path: cluster/platform/base/networking/egress-qos

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
