apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: oci://harbor.rcrumana.xyz/thirdparty-charts/external-secrets
    targetRevision: "2.2.0"
    path: .
    helm:
      values: |
        installCRDs: true
        crds:
          unsafeServeV1Beta1: true
        global:
          imagePullSecrets:
            - name: harbor-pull-creds
          repository: harbor.rcrumana.xyz/mirror/external-secrets/external-secrets
        replicaCount: 2
        serviceAccount:
          create: true
          name: external-secrets
        metrics:
          serviceMonitor:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
