apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      targetRevision: "1.18.3"
      chart: harbor
      helm:
        releaseName: harbor
        valueFiles:
          - $values/cluster/platform/registry/harbor/values.yaml
    - repoURL: https://github.com/rrumana/k8s-homelab-2.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/rrumana/k8s-homelab-2.git
      targetRevision: main
      path: cluster/platform/registry/harbor
      kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: harbor-core
      namespace: harbor
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: harbor-jobservice
      namespace: harbor
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: harbor-registry
      namespace: harbor
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: harbor-registry-htpasswd
      namespace: harbor
      jsonPointers:
        - /data
    - group: apps
      kind: Deployment
      name: harbor-core
      namespace: harbor
      jqPathExpressions:
        - '.spec.template.metadata.annotations."checksum/secret"'
        - '.spec.template.metadata.annotations."checksum/secret-jobservice"'
    - group: apps
      kind: Deployment
      name: harbor-jobservice
      namespace: harbor
      jqPathExpressions:
        - '.spec.template.metadata.annotations."checksum/secret"'
        - '.spec.template.metadata.annotations."checksum/secret-core"'
    - group: apps
      kind: Deployment
      name: harbor-registry
      namespace: harbor
      jqPathExpressions:
        - '.spec.template.metadata.annotations."checksum/secret"'
        - '.spec.template.metadata.annotations."checksum/secret-core"'
        - '.spec.template.metadata.annotations."checksum/secret-jobservice"'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: harbor
        app.kubernetes.io/managed-by: argocd
