apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  sources:
    - repoURL: harbor.rcrumana.xyz/thirdparty-charts
      chart: kube-prometheus-stack
      targetRevision: "80.13.3"
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/cluster/platform/observability/monitoring/values.yaml
    - repoURL: https://github.com/rrumana/k8s-homelab-2.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/rrumana/k8s-homelab-2.git
      targetRevision: main
      path: cluster/platform/observability/monitoring
      kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
