apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd2-cni
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: default
  sources:
    - repoURL: https://helm.linkerd.io/stable
      chart: linkerd2-cni
      targetRevision: "30.12.2"
      helm:
        releaseName: linkerd2-cni
        valueFiles:
          - $values/cluster/platform/service-mesh/linkerd/cni/values.yaml
    - repoURL: https://github.com/rrumana/k8s-homelab-2.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: service-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
