apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  project: default
  sources:
    - repoURL: https://helm.linkerd.io/stable
      chart: linkerd-viz
      targetRevision: "30.12.11"
      helm:
        releaseName: linkerd-viz
        valueFiles:
          - $values/cluster/platform/service-mesh/linkerd/viz/values.yaml
    - repoURL: https://github.com/rrumana/k8s-homelab-2.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: service-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # linkerd-viz includes Helm post-install hook resources (namespace-metadata)
      # which Argo applies via create; failed hook runs can leave resources
      # behind and cause subsequent syncs to fail with "already exists".
      - SkipHooks=true

  # cert-manager injects CA bundles into these resources; ignore those mutations
  # to avoid perpetual Argo diffs.
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: apiregistration.k8s.io
      kind: APIService
      name: v1alpha1.tap.linkerd.io
      jsonPointers:
        - /spec/caBundle
