apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-crds
    targetRevision: "1.8.0"
    helm:
      releaseName: linkerd-crds
      values: |
        # We manage Gateway API CRDs separately (and at newer versions).
        # The Linkerd CRDs chart includes an older HTTPRoute CRD which will
        # conflict with a v1 Gateway API install.
        enableHttpRoutes: false
  destination:
    server: https://kubernetes.default.svc
    namespace: service-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  # Some clusters default `spec.preserveUnknownFields: false` on CRDs, which can
  # cause perpetual (and harmless) drift.
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
