# platform/gitops/argocd/apps/metrics-server-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server/
      targetRevision: "3.13.0"
      chart: metrics-server
      helm:
        releaseName: metrics-server
        valueFiles:
          - $values/cluster/platform/scheduling/metrics-server/values.yaml

    - repoURL: https://github.com/rrumana/k8s-homelab-2.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
