# platform/gitops/argocd/apps/rook-ceph-temp-cluster-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-temp-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/rrumana/k8s-homelab-2.git
    targetRevision: main
    path: cluster/platform/base/storage/rook-ceph/temp-cluster

  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
