apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: search-monitors
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/rrumana/k8s-homelab-2.git
    targetRevision: main
    path: cluster/platform/observability/search/monitors
  destination:
    server: https://kubernetes.default.svc
    namespace: search
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
