# platform/gitops/argocd/apps/snapshot-controller-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  sources:
    - repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
      targetRevision: v8.2.0
      path: client/config/crd
    - repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
      targetRevision: v8.2.0
      path: deploy/kubernetes/snapshot-controller

  destination:
    server: https://kubernetes.default.svc
    namespace: backup

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
