apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey-queue
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  sources:
    - repoURL: oci://registry-1.docker.io/bitnamicharts/valkey
      targetRevision: "5.4.9"
      path: .
      helm:
        releaseName: valkey-queue
        valueFiles:
          - $values/cluster/platform/base/data/data-definitions/valkey/queue/values.yaml
    - repoURL: https://github.com/rrumana/k8s-homelab-2.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/rrumana/k8s-homelab-2.git
      targetRevision: main
      path: cluster/platform/base/data/data-definitions/valkey/queue
      kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
