apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
  labels:
    app: rook-ceph-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: rook-ceph-tools
          image: rook/ceph:v1.18.8
          command:
            - /bin/bash
            - -c
          args:
            - |
              set -e
              MON_HOST=$(echo "${ROOK_CEPH_MON_ENDPOINTS}" | sed -e 's/[a-z]=//g')
              cat > /etc/ceph/ceph.conf <<EOF
              [global]
                fsid = ${ROOK_CEPH_FSID}
                mon_host = ${MON_HOST}
              EOF
              cat > /etc/ceph/ceph.client.${ROOK_CEPH_USERNAME}.keyring <<EOF
              [client.${ROOK_CEPH_USERNAME}]
                key = ${ROOK_CEPH_SECRET}
              EOF
              sleep infinity
          env:
            - name: ROOK_CEPH_MON_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: rook-ceph-mon-endpoints
                  key: data
            - name: ROOK_CEPH_FSID
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: fsid
            - name: ROOK_CEPH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: ceph-username
            - name: ROOK_CEPH_SECRET
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: ceph-secret
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          tty: true
          stdin: true
          volumeMounts:
            - name: ceph-config
              mountPath: /etc/ceph
      volumes:
        - name: ceph-config
          emptyDir: {}
