apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
  labels:
    app: rook-ceph-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: rook-ceph-tools
          image: rook/ceph:v1.18.8
          command:
            - /bin/bash
            - -c
          args:
            - |
              set -e
              sleep infinity
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          tty: true
          stdin: true
          volumeMounts:
            - name: ceph-config
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
            - name: ceph-admin-keyring
              mountPath: /etc/ceph/ceph.client.admin.keyring
              subPath: keyring
      volumes:
        - name: ceph-config
          secret:
            secretName: rook-ceph-config
        - name: ceph-admin-keyring
          secret:
            secretName: rook-ceph-admin-keyring
