apiVersion: v1
kind: Service
metadata:
  name: headscale-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  selector:
    app: headscale
    component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
