apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale-postgres-data
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 10Gi
