apiVersion: batch/v1
kind: Job
metadata:
  name: restore-headscale-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: restore
          image: docker.io/library/postgres:17-alpine
          env:
            - name: PGHOST
              value: headscale-postgres
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: headscale-postgres
                  key: database
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: headscale-postgres
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: headscale-postgres
                  key: password
          command: ["/bin/sh", "-lc"]
          args:
            - |
              set -e
              DUMP_DIR="/nas/headscale/pgdump"
              DUMP_FILE="$(ls -1 ${DUMP_DIR}/headscale-*.dump 2>/dev/null | sort | tail -n1)"
              if [ -z "$DUMP_FILE" ]; then
                echo "no pgdump found in $DUMP_DIR"; exit 1
              fi
              for i in $(seq 1 60); do
                pg_isready -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" >/dev/null 2>&1 && break
                sleep 5
              done
              pg_isready -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" >/dev/null 2>&1 || {
                echo "postgres not ready"; exit 1; }
              pg_restore --no-owner --no-privileges --clean --if-exists -f /tmp/headscale-restore.sql "$DUMP_FILE"
              sed -i '/transaction_timeout/d' /tmp/headscale-restore.sql
              psql -v ON_ERROR_STOP=1 -d "$PGDATABASE" -f /tmp/headscale-restore.sql
          volumeMounts:
            - name: nas-migrate
              mountPath: /nas
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
      volumes:
        - name: nas-migrate
          hostPath:
            path: /NAS/Longhorn
            type: Directory
