apiVersion: v1
kind: ServiceAccount
metadata:
  name: headscale
imagePullSecrets:
  - name: harbor-pull-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headscale-ui
imagePullSecrets:
  - name: harbor-pull-creds
