apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: headscale
  namespace: other
spec:
  selector:
    matchLabels:
      app: headscale
  endpoints:
    - port: metrics
      interval: 30s
