apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core-secrets
  namespace: harbor
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: harbor-core-secrets
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: apps/harbor/core
        property: HARBOR_ADMIN_PASSWORD
    - secretKey: secretKey
      remoteRef:
        key: apps/harbor/core
        property: secretKey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-database-secrets
  namespace: harbor
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: harbor-database-secrets
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: apps/harbor/database
        property: password
