apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: truenas-https-1
  labels:
    kubernetes.io/service-name: truenas-https
addressType: IPv4
ports:
  - name: https
    protocol: TCP
    port: 443
endpoints:
  - addresses:
      - 192.168.1.10

