apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homarr-env
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: homarr-env
    creationPolicy: Owner
  data:
    - secretKey: DB_URL
      remoteRef:
        key: apps/productivity/homarr-env
        property: DB_URL
    - secretKey: SECRET_ENCRYPTION_KEY
      remoteRef:
        key: apps/productivity/homarr-env
        property: SECRET_ENCRYPTION_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homarr-helm-db-encryption
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: homarr-helm-db-encryption
    creationPolicy: Owner
  data:
    - secretKey: db-encryption-key
      remoteRef:
        key: apps/productivity/homarr-helm-db-encryption
        property: db-encryption-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homarr-helm-db-postgres
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: homarr-helm-db-postgres
    creationPolicy: Owner
  data:
    - secretKey: db-url
      remoteRef:
        key: apps/productivity/homarr-helm-db-postgres
        property: db-url
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homarr-managed-runtime
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: homarr-managed-runtime
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: apps/productivity/homarr-managed-runtime
        property: DB_PASSWORD
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: apps/productivity/homarr-managed-runtime
        property: REDIS_PASSWORD
