apiVersion: v1
kind: Service
metadata:
  name: homarr-helm-mysql
  labels:
    app: homarr-helm
    component: mysql
spec:
  type: ClusterIP
  selector:
    app: homarr-helm
    component: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
