apiVersion: batch/v1
kind: Job
metadata:
  name: restore-homarr-mysql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: restore
          image: mysql:8.4
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homarr-helm-mysql
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: homarr-helm-mysql
                  key: MYSQL_DATABASE
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              DUMP_DIR="/nas/homarr-helm/mysqldump"
              DUMP_FILE="$(ls -1 ${DUMP_DIR}/homarr-helm-*.sql 2>/dev/null | sort | tail -n1)"
              if [ -z "$DUMP_FILE" ]; then
                echo "no mysql dump found in $DUMP_DIR"; exit 1
              fi
              for i in $(seq 1 60); do
                mysqladmin ping -h homarr-helm-mysql -uroot -p"$MYSQL_ROOT_PASSWORD" >/dev/null 2>&1 && break
                sleep 5
              done
              mysqladmin ping -h homarr-helm-mysql -uroot -p"$MYSQL_ROOT_PASSWORD" >/dev/null 2>&1 || {
                echo "mysql not ready"; exit 1; }
              mysql -h homarr-helm-mysql -uroot -p"$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE" < "$DUMP_FILE"
          volumeMounts:
            - name: nas-migrate
              mountPath: /nas
              readOnly: true
      volumes:
        - name: nas-migrate
          hostPath:
            path: /NAS/Longhorn
            type: Directory
