apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: volsync-minio
  namespace: other
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: volsync-minio
    creationPolicy: Owner
  data:
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: apps/other/volsync-minio
        property: RESTIC_REPOSITORY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: apps/other/volsync-minio
        property: RESTIC_PASSWORD
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: apps/other/volsync-minio
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: apps/other/volsync-minio
        property: AWS_SECRET_ACCESS_KEY
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: headscale-data-backup
  namespace: other
spec:
  sourcePVC: headscale-data
  trigger:
    schedule: "5 4 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: volsync-minio
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: headscale-postgres-data-backup
  namespace: other
spec:
  sourcePVC: headscale-postgres-data
  trigger:
    schedule: "20 4 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: volsync-minio
    pruneIntervalDays: 3650
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
