apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: volsync-minio
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: volsync-minio
    creationPolicy: Owner
  data:
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: apps/productivity/volsync-minio
        property: RESTIC_REPOSITORY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: apps/productivity/volsync-minio
        property: RESTIC_PASSWORD
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: apps/productivity/volsync-minio
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: apps/productivity/volsync-minio
        property: AWS_SECRET_ACCESS_KEY
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: data-homarr-helm-mysql-0-backup
  namespace: productivity
spec:
  sourcePVC: data-homarr-helm-mysql-0
  trigger:
    schedule: "35 4 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: volsync-minio
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: data-homarr-redis-0-backup
  namespace: productivity
spec:
  sourcePVC: data-homarr-redis-0
  trigger:
    schedule: "50 4 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: volsync-minio
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: elasticsearch-data-backup
  namespace: productivity
spec:
  sourcePVC: elasticsearch-data
  trigger:
    schedule: "5 5 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: volsync-minio
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: nextcloud-appdata-backup
  namespace: productivity
spec:
  sourcePVC: nextcloud-appdata
  trigger:
    schedule: "20 5 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: volsync-minio
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: nextcloud-postgresql-data-backup
  namespace: productivity
spec:
  sourcePVC: nextcloud-postgresql-data
  trigger:
    schedule: "35 5 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: volsync-minio
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: nextcloud-redis-data-backup
  namespace: productivity
spec:
  sourcePVC: nextcloud-redis-data
  trigger:
    schedule: "50 5 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: volsync-minio
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: unifi-config-backup
  namespace: productivity
spec:
  sourcePVC: unifi-config
  trigger:
    schedule: "5 6 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: volsync-minio
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: unifi-db-backup
  namespace: productivity
spec:
  sourcePVC: unifi-db
  trigger:
    schedule: "20 6 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: volsync-minio
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: uptime-kuma-data-backup
  namespace: productivity
spec:
  sourcePVC: uptime-kuma-data
  trigger:
    schedule: "35 6 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: volsync-minio
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vaultwarden-data-backup
  namespace: productivity
spec:
  sourcePVC: vaultwarden-data
  trigger:
    schedule: "50 6 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: volsync-minio
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
