apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: volsync-minio
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: volsync-minio
    creationPolicy: Owner
  data:
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: apps/productivity/volsync-minio
        property: RESTIC_REPOSITORY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: apps/productivity/volsync-minio
        property: RESTIC_PASSWORD
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: apps/productivity/volsync-minio
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: apps/productivity/volsync-minio
        property: AWS_SECRET_ACCESS_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: elasticsearch-data-backup-restic
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: elasticsearch-data-backup-restic
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .resticRepository }}/elasticsearch-data-backup"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
        AWS_ACCESS_KEY_ID: "{{ .awsAccessKeyId }}"
        AWS_SECRET_ACCESS_KEY: "{{ .awsSecretAccessKey }}"
  data:
    - secretKey: resticRepository
      remoteRef:
        key: apps/productivity/volsync-minio
        property: RESTIC_REPOSITORY
    - secretKey: resticPassword
      remoteRef:
        key: apps/productivity/volsync-minio
        property: RESTIC_PASSWORD
    - secretKey: awsAccessKeyId
      remoteRef:
        key: apps/productivity/volsync-minio
        property: AWS_ACCESS_KEY_ID
    - secretKey: awsSecretAccessKey
      remoteRef:
        key: apps/productivity/volsync-minio
        property: AWS_SECRET_ACCESS_KEY
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: elasticsearch-data-backup
  namespace: productivity
spec:
  sourcePVC: elasticsearch-data
  trigger:
    schedule: "5 5 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: elasticsearch-data-backup-restic
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-appdata-backup-restic
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: nextcloud-appdata-backup-restic
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .resticRepository }}/nextcloud-appdata-backup"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
        AWS_ACCESS_KEY_ID: "{{ .awsAccessKeyId }}"
        AWS_SECRET_ACCESS_KEY: "{{ .awsSecretAccessKey }}"
  data:
    - secretKey: resticRepository
      remoteRef:
        key: apps/productivity/volsync-minio
        property: RESTIC_REPOSITORY
    - secretKey: resticPassword
      remoteRef:
        key: apps/productivity/volsync-minio
        property: RESTIC_PASSWORD
    - secretKey: awsAccessKeyId
      remoteRef:
        key: apps/productivity/volsync-minio
        property: AWS_ACCESS_KEY_ID
    - secretKey: awsSecretAccessKey
      remoteRef:
        key: apps/productivity/volsync-minio
        property: AWS_SECRET_ACCESS_KEY
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: nextcloud-appdata-backup
  namespace: productivity
spec:
  sourcePVC: nextcloud-appdata
  trigger:
    schedule: "20 5 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: nextcloud-appdata-backup-restic
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: uptime-kuma-data-backup-restic
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: uptime-kuma-data-backup-restic
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .resticRepository }}/uptime-kuma-data-backup"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
        AWS_ACCESS_KEY_ID: "{{ .awsAccessKeyId }}"
        AWS_SECRET_ACCESS_KEY: "{{ .awsSecretAccessKey }}"
  data:
    - secretKey: resticRepository
      remoteRef:
        key: apps/productivity/volsync-minio
        property: RESTIC_REPOSITORY
    - secretKey: resticPassword
      remoteRef:
        key: apps/productivity/volsync-minio
        property: RESTIC_PASSWORD
    - secretKey: awsAccessKeyId
      remoteRef:
        key: apps/productivity/volsync-minio
        property: AWS_ACCESS_KEY_ID
    - secretKey: awsSecretAccessKey
      remoteRef:
        key: apps/productivity/volsync-minio
        property: AWS_SECRET_ACCESS_KEY
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: uptime-kuma-data-backup
  namespace: productivity
spec:
  sourcePVC: uptime-kuma-data
  trigger:
    schedule: "35 6 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: uptime-kuma-data-backup-restic
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-data-backup-restic
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: vaultwarden-data-backup-restic
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .resticRepository }}/vaultwarden-data-backup"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
        AWS_ACCESS_KEY_ID: "{{ .awsAccessKeyId }}"
        AWS_SECRET_ACCESS_KEY: "{{ .awsSecretAccessKey }}"
  data:
    - secretKey: resticRepository
      remoteRef:
        key: apps/productivity/volsync-minio
        property: RESTIC_REPOSITORY
    - secretKey: resticPassword
      remoteRef:
        key: apps/productivity/volsync-minio
        property: RESTIC_PASSWORD
    - secretKey: awsAccessKeyId
      remoteRef:
        key: apps/productivity/volsync-minio
        property: AWS_ACCESS_KEY_ID
    - secretKey: awsSecretAccessKey
      remoteRef:
        key: apps/productivity/volsync-minio
        property: AWS_SECRET_ACCESS_KEY
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vaultwarden-data-backup
  namespace: productivity
spec:
  sourcePVC: vaultwarden-data
  trigger:
    schedule: "50 6 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block-snap
    repository: vaultwarden-data-backup-restic
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      weekly: 4
      monthly: 3
