# Manual one-time migration job.
# This file is intentionally not included in kustomization.yaml.
# Apply it only during a planned maintenance window:
# kubectl apply -f cluster/apps/media/arr/migrate-servarr-sqlite-to-postgres-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-servarr-sqlite-to-postgres
  namespace: media
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/ralgar/pgloader:pr-1531
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: arr-postgres-config
            - secretRef:
                name: arr-postgres-secret
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eu

              find_db() {
                dir="$1"; shift
                for name in "$@"; do
                  if [ -f "${dir}/${name}" ]; then
                    echo "${dir}/${name}"
                    return 0
                  fi
                done
                return 1
              }

              migrate_sqlite_db() {
                app="$1"
                sqlite_path="$2"
                pg_user="$3"
                pg_password="$4"
                pg_db="$5"

                if [ ! -f "${sqlite_path}" ]; then
                  echo "[${app}] sqlite file missing: ${sqlite_path}"
                  return 1
                fi

                echo "[${app}] migrating ${sqlite_path} -> ${pg_db}"
                PGPASSWORD="${pg_password}" pgloader \
                  --with "data only" \
                  --with "truncate" \
                  --with "quote identifiers" \
                  "sqlite:///${sqlite_path}" \
                  "postgresql://${pg_user}@${ARR_PG_HOST}:${ARR_PG_PORT}/${pg_db}"
              }

              SONARR_MAIN="$(find_db /data/sonarr sonarr.db nzbdrone.db)"
              RADARR_MAIN="$(find_db /data/radarr radarr.db nzbdrone.db)"
              LIDARR_MAIN="$(find_db /data/lidarr lidarr.db nzbdrone.db)"
              PROWLARR_MAIN="$(find_db /data/prowlarr prowlarr.db nzbdrone.db)"

              migrate_sqlite_db sonarr-main "${SONARR_MAIN}" "${SONARR_PG_USER}" "${SONARR_PG_PASSWORD}" "${SONARR_PG_MAIN_DB}"
              migrate_sqlite_db radarr-main "${RADARR_MAIN}" "${RADARR_PG_USER}" "${RADARR_PG_PASSWORD}" "${RADARR_PG_MAIN_DB}"
              migrate_sqlite_db lidarr-main "${LIDARR_MAIN}" "${LIDARR_PG_USER}" "${LIDARR_PG_PASSWORD}" "${LIDARR_PG_MAIN_DB}"
              migrate_sqlite_db prowlarr-main "${PROWLARR_MAIN}" "${PROWLARR_PG_USER}" "${PROWLARR_PG_PASSWORD}" "${PROWLARR_PG_MAIN_DB}"

              if [ -f /data/sonarr/logs.db ]; then
                migrate_sqlite_db sonarr-log /data/sonarr/logs.db "${SONARR_PG_USER}" "${SONARR_PG_PASSWORD}" "${SONARR_PG_LOG_DB}"
              fi
              if [ -f /data/radarr/logs.db ]; then
                migrate_sqlite_db radarr-log /data/radarr/logs.db "${RADARR_PG_USER}" "${RADARR_PG_PASSWORD}" "${RADARR_PG_LOG_DB}"
              fi
              if [ -f /data/lidarr/logs.db ]; then
                migrate_sqlite_db lidarr-log /data/lidarr/logs.db "${LIDARR_PG_USER}" "${LIDARR_PG_PASSWORD}" "${LIDARR_PG_LOG_DB}"
              fi
              if [ -f /data/prowlarr/logs.db ]; then
                migrate_sqlite_db prowlarr-log /data/prowlarr/logs.db "${PROWLARR_PG_USER}" "${PROWLARR_PG_PASSWORD}" "${PROWLARR_PG_LOG_DB}"
              fi

              echo "All requested Servarr database migrations completed."
          volumeMounts:
            - name: sonarr-config
              mountPath: /data/sonarr
              readOnly: true
            - name: radarr-config
              mountPath: /data/radarr
              readOnly: true
            - name: lidarr-config
              mountPath: /data/lidarr
              readOnly: true
            - name: prowlarr-config
              mountPath: /data/prowlarr
              readOnly: true
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: arr-stack-sonarr-config
        - name: radarr-config
          persistentVolumeClaim:
            claimName: arr-stack-radarr-config
        - name: lidarr-config
          persistentVolumeClaim:
            claimName: arr-stack-lidarr-config
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: arr-stack-prowlarr-config
