apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: productivity

resources:
  - pvc.yaml
  - deployment.yaml
  - service-ui.yaml
  - service-tcp.yaml
  - service-udp.yaml
  - vpa.yaml

commonLabels:
  app.kubernetes.io/name: unifi-os-server
  app.kubernetes.io/managed-by: argocd
