apiVersion: v1
kind: Service
metadata:
  name: unifi-os-server-ui
spec:
  type: ClusterIP
  selector:
    app: unifi-os-server
  ports:
    - name: https
      port: 11443
      targetPort: 443
      protocol: TCP
