apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: data-prepper-pipeline
  namespace: search
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: data-prepper-pipeline
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        pipelines.yaml: |
          entry-pipeline:
            source:
              http:
                path: /logs
                health_check_service: true
                unauthenticated_health_check: true
            processor:
              - date:
                  from_time_received: true
                  destination: "@timestamp"
            sink:
              - opensearch:
                  hosts:
                    - "https://opensearch-logs:9200"
                  insecure: true
                  username: "{{ .username }}"
                  password: "{{ .password }}"
                  index_type: custom
                  index: "logs-%{yyyy.MM.dd}"
  data:
    - secretKey: username
      remoteRef:
        key: apps/search/opensearch-admin
        property: username
    - secretKey: password
      remoteRef:
        key: apps/search/opensearch-admin
        property: password
