apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: search
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  selector:
    app.kubernetes.io/name: fluent-bit
  ports:
    - name: http-metrics
      port: 2020
      targetPort: http-metrics
