apiVersion: opensearch.org/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-logs
  namespace: search
spec:
  general:
    serviceName: opensearch-logs
    version: "3.4.0"
    image: harbor.rcrumana.xyz/mirror/opensearchproject/opensearch
    vendor: Opensearch
    serviceAccount: opensearch-logs
    setVMMaxMapCount: true
  initHelper:
    image: harbor.rcrumana.xyz/mirror/library/busybox
    version: "1.36"
  dashboards:
    enable: false
  security:
    tls:
      transport:
        generate: true
        perNode: true
      http:
        generate: true
    config:
      adminCredentialsSecret:
        name: opensearch-admin-credentials
  nodePools:
    - component: logs
      replicas: 3
      diskSize: "200Gi"
      jvm: "-Xms2g -Xmx2g"
      resources:
        requests:
          cpu: "1"
          memory: 4Gi
        limits:
          cpu: "4"
          memory: 8Gi
      env:
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: opensearch-admin-credentials
              key: password
      roles:
        - cluster_manager
        - data
        - ingest
