manager:
  image:
    repository: harbor.rcrumana.xyz/mirror/opensearchproject/opensearch-operator
    tag: "2.8.0"
    pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: harbor-pull-creds
  loglevel: info
  watchNamespace:
    - search

kubeRbacProxy:
  image:
    repository: harbor.rcrumana.xyz/mirror/brancz/kube-rbac-proxy
    tag: "v0.15.0"
