apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: foldingathome
  labels:
    app: foldingathome
spec:
  serviceName: foldingathome
  replicas: 3
  podManagementPolicy: Parallel
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: foldingathome
  template:
    metadata:
      labels:
        app: foldingathome
    spec:
      serviceAccountName: foldingathome
      terminationGracePeriodSeconds: 300
      enableServiceLinks: false
      securityContext:
        fsGroup: 1000
        supplementalGroups:
          - 985
          - 989
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: foldingathome
              topologyKey: kubernetes.io/hostname
      containers:
        - name: foldingathome
          image: harbor.rcrumana.xyz/proxy-dockerhub/linuxserver/foldingathome:8.5.5
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 7396
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Los_Angeles
            - name: HSA_OVERRIDE_GFX_VERSION
              value: "11.5.1"
            - name: ACCOUNT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: foldingathome
                  key: ACCOUNT_TOKEN
            - name: MACHINE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
              amd.com/gpu: "1"
            limits:
              cpu: "12"
              memory: 8Gi
              amd.com/gpu: "1"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: dri
              mountPath: /dev/dri
            - name: kfd
              mountPath: /dev/kfd
      volumes:
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
        - name: kfd
          hostPath:
            path: /dev/kfd
            type: CharDevice
  volumeClaimTemplates:
    - metadata:
        name: config
        annotations:
          argocd.argoproj.io/sync-wave: "-20"
      spec:
        storageClassName: ceph-block
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
