apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: renovate-secrets
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: apps/automation/renovate
        property: RENOVATE_TOKEN
    - secretKey: HARBOR_USERNAME
      remoteRef:
        key: apps/automation/renovate
        property: HARBOR_USERNAME
    - secretKey: HARBOR_PASSWORD
      remoteRef:
        key: apps/automation/renovate
        property: HARBOR_PASSWORD
