apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-lts-qbit-config
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-lts-gluetun
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 256Mi
