apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-homarr-env
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: homarr-env
  data:
    - match:
        secretKey: DB_URL
        remoteRef:
          remoteKey: apps/productivity/homarr-env
          property: DB_URL
    - match:
        secretKey: SECRET_ENCRYPTION_KEY
        remoteRef:
          remoteKey: apps/productivity/homarr-env
          property: SECRET_ENCRYPTION_KEY
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-homarr-helm-db
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: homarr-helm-db
  data:
    - match:
        secretKey: db-url
        remoteRef:
          remoteKey: apps/productivity/homarr-helm-db
          property: db-url
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-homarr-helm-db-encryption
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: homarr-helm-db-encryption
  data:
    - match:
        secretKey: db-encryption-key
        remoteRef:
          remoteKey: apps/productivity/homarr-helm-db-encryption
          property: db-encryption-key
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-homarr-helm-mysql
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: homarr-helm-mysql
  data:
    - match:
        secretKey: MYSQL_DATABASE
        remoteRef:
          remoteKey: apps/productivity/homarr-helm-mysql
          property: MYSQL_DATABASE
    - match:
        secretKey: MYSQL_PASSWORD
        remoteRef:
          remoteKey: apps/productivity/homarr-helm-mysql
          property: MYSQL_PASSWORD
    - match:
        secretKey: MYSQL_ROOT_PASSWORD
        remoteRef:
          remoteKey: apps/productivity/homarr-helm-mysql
          property: MYSQL_ROOT_PASSWORD
    - match:
        secretKey: MYSQL_USER
        remoteRef:
          remoteKey: apps/productivity/homarr-helm-mysql
          property: MYSQL_USER
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-homarr-mysql-secret
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: homarr-mysql-secret
  data:
    - match:
        secretKey: mysql-password
        remoteRef:
          remoteKey: apps/productivity/homarr-mysql-secret
          property: mysql-password
    - match:
        secretKey: mysql-replication-password
        remoteRef:
          remoteKey: apps/productivity/homarr-mysql-secret
          property: mysql-replication-password
    - match:
        secretKey: mysql-root-password
        remoteRef:
          remoteKey: apps/productivity/homarr-mysql-secret
          property: mysql-root-password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-homarr-redis
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: homarr-redis
  data:
    - match:
        secretKey: redis-password
        remoteRef:
          remoteKey: apps/productivity/homarr-redis
          property: redis-password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-nextcloud-admin
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: nextcloud-admin
  data:
    - match:
        secretKey: nextcloud-username
        remoteRef:
          remoteKey: apps/productivity/nextcloud-admin
          property: nextcloud-username
    - match:
        secretKey: nextcloud-password
        remoteRef:
          remoteKey: apps/productivity/nextcloud-admin
          property: nextcloud-password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-nextcloud-db
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: nextcloud-db
  data:
    - match:
        secretKey: db-username
        remoteRef:
          remoteKey: apps/productivity/nextcloud-db
          property: db-username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: apps/productivity/nextcloud-db
          property: password
    - match:
        secretKey: postgres-password
        remoteRef:
          remoteKey: apps/productivity/nextcloud-db
          property: postgres-password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-nextcloud-redis
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: nextcloud-redis
  data:
    - match:
        secretKey: redis-password
        remoteRef:
          remoteKey: apps/productivity/nextcloud-redis
          property: redis-password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-cloudflare-origin-default-cert
  namespace: ingress-haproxy
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: cloudflare-origin-default-cert
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: apps/ingress-haproxy/cloudflare-origin-default-cert
          property: tls.crt
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: apps/ingress-haproxy/cloudflare-origin-default-cert
          property: tls.key
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-linkerd-trust-anchor
  namespace: service-mesh
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: linkerd-trust-anchor
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: apps/service-mesh/linkerd-trust-anchor
          property: tls.crt
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: apps/service-mesh/linkerd-trust-anchor
          property: tls.key
