apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-gluetun-env
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: gluetun-env
  data:
    - match:
        secretKey: VPN_ENDPOINT_IP
        remoteRef:
          remoteKey: apps/media/gluetun-env
          property: VPN_ENDPOINT_IP
    - match:
        secretKey: VPN_ENDPOINT_PORT
        remoteRef:
          remoteKey: apps/media/gluetun-env
          property: VPN_ENDPOINT_PORT
    - match:
        secretKey: VPN_PORT_FORWARDING
        remoteRef:
          remoteKey: apps/media/gluetun-env
          property: VPN_PORT_FORWARDING
    - match:
        secretKey: VPN_PORT_FORWARDING_PROVIDER
        remoteRef:
          remoteKey: apps/media/gluetun-env
          property: VPN_PORT_FORWARDING_PROVIDER
    - match:
        secretKey: VPN_SERVICE_PROVIDER
        remoteRef:
          remoteKey: apps/media/gluetun-env
          property: VPN_SERVICE_PROVIDER
    - match:
        secretKey: VPN_TYPE
        remoteRef:
          remoteKey: apps/media/gluetun-env
          property: VPN_TYPE
    - match:
        secretKey: WIREGUARD_ADDRESSES
        remoteRef:
          remoteKey: apps/media/gluetun-env
          property: WIREGUARD_ADDRESSES
    - match:
        secretKey: WIREGUARD_MTU
        remoteRef:
          remoteKey: apps/media/gluetun-env
          property: WIREGUARD_MTU
    - match:
        secretKey: WIREGUARD_PRIVATE_KEY
        remoteRef:
          remoteKey: apps/media/gluetun-env
          property: WIREGUARD_PRIVATE_KEY
    - match:
        secretKey: WIREGUARD_PUBLIC_KEY
        remoteRef:
          remoteKey: apps/media/gluetun-env
          property: WIREGUARD_PUBLIC_KEY
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-gluetun-lts-env
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: gluetun-lts-env
  data:
    - match:
        secretKey: VPN_ENDPOINT_IP
        remoteRef:
          remoteKey: apps/media/gluetun-lts-env
          property: VPN_ENDPOINT_IP
    - match:
        secretKey: VPN_ENDPOINT_PORT
        remoteRef:
          remoteKey: apps/media/gluetun-lts-env
          property: VPN_ENDPOINT_PORT
    - match:
        secretKey: VPN_PORT_FORWARDING
        remoteRef:
          remoteKey: apps/media/gluetun-lts-env
          property: VPN_PORT_FORWARDING
    - match:
        secretKey: VPN_PORT_FORWARDING_PROVIDER
        remoteRef:
          remoteKey: apps/media/gluetun-lts-env
          property: VPN_PORT_FORWARDING_PROVIDER
    - match:
        secretKey: VPN_SERVICE_PROVIDER
        remoteRef:
          remoteKey: apps/media/gluetun-lts-env
          property: VPN_SERVICE_PROVIDER
    - match:
        secretKey: VPN_TYPE
        remoteRef:
          remoteKey: apps/media/gluetun-lts-env
          property: VPN_TYPE
    - match:
        secretKey: WIREGUARD_ADDRESSES
        remoteRef:
          remoteKey: apps/media/gluetun-lts-env
          property: WIREGUARD_ADDRESSES
    - match:
        secretKey: WIREGUARD_MTU
        remoteRef:
          remoteKey: apps/media/gluetun-lts-env
          property: WIREGUARD_MTU
    - match:
        secretKey: WIREGUARD_PRIVATE_KEY
        remoteRef:
          remoteKey: apps/media/gluetun-lts-env
          property: WIREGUARD_PRIVATE_KEY
    - match:
        secretKey: WIREGUARD_PUBLIC_KEY
        remoteRef:
          remoteKey: apps/media/gluetun-lts-env
          property: WIREGUARD_PUBLIC_KEY
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-gluetun-lts2-env
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: gluetun-lts2-env
  data:
    - match:
        secretKey: VPN_ENDPOINT_IP
        remoteRef:
          remoteKey: apps/media/gluetun-lts2-env
          property: VPN_ENDPOINT_IP
    - match:
        secretKey: VPN_ENDPOINT_PORT
        remoteRef:
          remoteKey: apps/media/gluetun-lts2-env
          property: VPN_ENDPOINT_PORT
    - match:
        secretKey: VPN_PORT_FORWARDING
        remoteRef:
          remoteKey: apps/media/gluetun-lts2-env
          property: VPN_PORT_FORWARDING
    - match:
        secretKey: VPN_PORT_FORWARDING_PROVIDER
        remoteRef:
          remoteKey: apps/media/gluetun-lts2-env
          property: VPN_PORT_FORWARDING_PROVIDER
    - match:
        secretKey: VPN_SERVICE_PROVIDER
        remoteRef:
          remoteKey: apps/media/gluetun-lts2-env
          property: VPN_SERVICE_PROVIDER
    - match:
        secretKey: VPN_TYPE
        remoteRef:
          remoteKey: apps/media/gluetun-lts2-env
          property: VPN_TYPE
    - match:
        secretKey: WIREGUARD_ADDRESSES
        remoteRef:
          remoteKey: apps/media/gluetun-lts2-env
          property: WIREGUARD_ADDRESSES
    - match:
        secretKey: WIREGUARD_MTU
        remoteRef:
          remoteKey: apps/media/gluetun-lts2-env
          property: WIREGUARD_MTU
    - match:
        secretKey: WIREGUARD_PRIVATE_KEY
        remoteRef:
          remoteKey: apps/media/gluetun-lts2-env
          property: WIREGUARD_PRIVATE_KEY
    - match:
        secretKey: WIREGUARD_PUBLIC_KEY
        remoteRef:
          remoteKey: apps/media/gluetun-lts2-env
          property: WIREGUARD_PUBLIC_KEY
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-immich-secret
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: immich-secret
  data:
    - match:
        secretKey: DB_PASSWORD
        remoteRef:
          remoteKey: apps/media/immich-secret
          property: DB_PASSWORD
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-qb-lts-webui-creds
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: qb-lts-webui-creds
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: apps/media/qb-lts-webui-creds
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: apps/media/qb-lts-webui-creds
          property: password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-qb-lts2-webui-creds
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: qb-lts2-webui-creds
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: apps/media/qb-lts2-webui-creds
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: apps/media/qb-lts2-webui-creds
          property: password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-qb-webui-creds
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: qb-webui-creds
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: apps/media/qb-webui-creds
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: apps/media/qb-webui-creds
          property: password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-headscale-postgres
  namespace: other
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: headscale-postgres
  data:
    - match:
        secretKey: database
        remoteRef:
          remoteKey: apps/other/headscale-postgres
          property: database
    - match:
        secretKey: password
        remoteRef:
          remoteKey: apps/other/headscale-postgres
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: apps/other/headscale-postgres
          property: username
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-homarr-env
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: homarr-env
  data:
    - match:
        secretKey: DB_URL
        remoteRef:
          remoteKey: apps/productivity/homarr-env
          property: DB_URL
    - match:
        secretKey: SECRET_ENCRYPTION_KEY
        remoteRef:
          remoteKey: apps/productivity/homarr-env
          property: SECRET_ENCRYPTION_KEY
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-homarr-helm-db
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: homarr-helm-db
  data:
    - match:
        secretKey: db-url
        remoteRef:
          remoteKey: apps/productivity/homarr-helm-db
          property: db-url
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-homarr-helm-db-encryption
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: homarr-helm-db-encryption
  data:
    - match:
        secretKey: db-encryption-key
        remoteRef:
          remoteKey: apps/productivity/homarr-helm-db-encryption
          property: db-encryption-key
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-homarr-helm-mysql
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: homarr-helm-mysql
  data:
    - match:
        secretKey: MYSQL_DATABASE
        remoteRef:
          remoteKey: apps/productivity/homarr-helm-mysql
          property: MYSQL_DATABASE
    - match:
        secretKey: MYSQL_PASSWORD
        remoteRef:
          remoteKey: apps/productivity/homarr-helm-mysql
          property: MYSQL_PASSWORD
    - match:
        secretKey: MYSQL_ROOT_PASSWORD
        remoteRef:
          remoteKey: apps/productivity/homarr-helm-mysql
          property: MYSQL_ROOT_PASSWORD
    - match:
        secretKey: MYSQL_USER
        remoteRef:
          remoteKey: apps/productivity/homarr-helm-mysql
          property: MYSQL_USER
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-homarr-mysql-secret
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: homarr-mysql-secret
  data:
    - match:
        secretKey: mysql-password
        remoteRef:
          remoteKey: apps/productivity/homarr-mysql-secret
          property: mysql-password
    - match:
        secretKey: mysql-replication-password
        remoteRef:
          remoteKey: apps/productivity/homarr-mysql-secret
          property: mysql-replication-password
    - match:
        secretKey: mysql-root-password
        remoteRef:
          remoteKey: apps/productivity/homarr-mysql-secret
          property: mysql-root-password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-homarr-redis
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: homarr-redis
  data:
    - match:
        secretKey: redis-password
        remoteRef:
          remoteKey: apps/productivity/homarr-redis
          property: redis-password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-nextcloud-admin
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: nextcloud-admin
  data:
    - match:
        secretKey: nextcloud-username
        remoteRef:
          remoteKey: apps/productivity/nextcloud-admin
          property: nextcloud-username
    - match:
        secretKey: nextcloud-password
        remoteRef:
          remoteKey: apps/productivity/nextcloud-admin
          property: nextcloud-password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-nextcloud-db
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: nextcloud-db
  data:
    - match:
        secretKey: db-username
        remoteRef:
          remoteKey: apps/productivity/nextcloud-db
          property: db-username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: apps/productivity/nextcloud-db
          property: password
    - match:
        secretKey: postgres-password
        remoteRef:
          remoteKey: apps/productivity/nextcloud-db
          property: postgres-password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-nextcloud-redis
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: nextcloud-redis
  data:
    - match:
        secretKey: redis-password
        remoteRef:
          remoteKey: apps/productivity/nextcloud-redis
          property: redis-password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-unifi-db-credentials
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: unifi-db-credentials
  data:
    - match:
        secretKey: MONGO_PASS
        remoteRef:
          remoteKey: apps/productivity/unifi-db-credentials
          property: MONGO_PASS
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-unifi-db-credentials
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: unifi-db-credentials
  data:
    - match:
        secretKey: MONGO_PASS
        remoteRef:
          remoteKey: apps/productivity/unifi-db-credentials
          property: MONGO_PASS
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-ghcr-creds
  namespace: web
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: ghcr-creds
  data:
    - match:
        secretKey: .dockerconfigjson
        remoteRef:
          remoteKey: apps/web/ghcr-creds
          property: .dockerconfigjson
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-cloudflare-origin-default-cert
  namespace: ingress-haproxy
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: cloudflare-origin-default-cert
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: apps/ingress-haproxy/cloudflare-origin-default-cert
          property: tls.crt
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: apps/ingress-haproxy/cloudflare-origin-default-cert
          property: tls.key
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-linkerd-trust-anchor
  namespace: service-mesh
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: linkerd-trust-anchor
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: apps/service-mesh/linkerd-trust-anchor
          property: tls.crt
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: apps/service-mesh/linkerd-trust-anchor
          property: tls.key
