apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook

  # Reef (18) is a stable choice for a homelab; this is a temp single-node cluster anyway.
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.2

  # TEMP / DEV ONLY:
  # One mon = no quorum; do not store important data until you have 3+ Ceph nodes.
  mon:
    count: 1
    allowMultiplePerNode: false

  mgr:
    count: 1
    allowMultiplePerNode: false

  # Pin all Ceph daemons to melchior-1 so balthasar-2 (no data disks yet) is never used.
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - melchior-1
      tolerations:
        - operator: Exists

  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: melchior-1
        devices:
          - name: nvme0n1
          - name: nvme2n1

