apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkerd-trust-anchor
  namespace: service-mesh
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: linkerd-trust-anchor
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: apps/service-mesh/linkerd-trust-anchor
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: apps/service-mesh/linkerd-trust-anchor
        property: tls.key
