imagePullSecrets:
  - name: harbor-pull-creds

controller:
  image:
    repository: harbor.rcrumana.xyz/mirror/metallb/controller
    tag: v0.15.3
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi
  
  # Enable Prometheus metrics
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

speaker:
  image:
    repository: harbor.rcrumana.xyz/mirror/metallb/speaker
    tag: v0.15.3
  frr:
    image:
      repository: harbor.rcrumana.xyz/mirror/frrouting/frr
      tag: 10.4.1
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi
  
  # Enable Prometheus metrics
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  
  tolerateMaster: true

# CRDs are included in the chart
crds:
  enabled: true
  validationFailurePolicy: Fail
