apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secret
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        REDIS_URL: 'ioredis://{{ printf "{\"sentinels\":[{\"host\":\"valkey-queue.databases.svc.cluster.local\",\"port\":26379}],\"name\":\"valkey-queue\",\"password\":\"%s\",\"sentinelPassword\":\"%s\"}" .REDIS_PASSWORD .REDIS_PASSWORD | b64enc }}'
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: apps/media/immich-secret
        property: DB_PASSWORD
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: apps/databases/valkey-queue-auth
        property: password
