apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  labels:
    app: immich
    component: machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich
      component: machine-learning
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: immich
        component: machine-learning
    spec:
      serviceAccountName: immich-machine-learning
      containers:
        - name: immich-machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:v2.5.6-rocm
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: immich-config
            - secretRef:
                name: immich-secret
          env:
            - name: HSA_OVERRIDE_GFX_VERSION
              value: "11.0.0"
            - name: HSA_USE_SVM
              value: "0"
            - name: MACHINE_LEARNING_WORKER_TIMEOUT
              value: "300"
            - name: MACHINE_LEARNING_CACHE_FOLDER
              value: "/cache"
            - name: MACHINE_LEARNING_REQUEST_THREADS
              value: "1"
            - name: MACHINE_LEARNING_MODEL_INTRA_OP_THREADS
              value: "1"
            - name: MACHINE_LEARNING_WORKERS
              value: "1"
          volumeMounts:
            - name: model-cache
              mountPath: /cache
            - name: dri
              mountPath: /dev/dri
            - name: kfd
              mountPath: /dev/kfd
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "8Gi"
              cpu: "24"
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: immich-ml-cache
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
        - name: kfd
          hostPath:
            path: /dev/kfd
            type: CharDevice
