apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpa-recommender
  namespace: scheduling
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:vpa-status-actuator
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups: [""]
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups: [""]
    resources:
      - pods/eviction
    verbs:
      - create
  - apiGroups: [""]
    resources:
      - pods
      - replicationcontrollers
      - persistentvolumeclaims
      - nodes
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups: [autoscaling.k8s.io]
    resources:
      - verticalpodautoscalers
      - verticalpodautoscalers/status
      - verticalpodautoscalercheckpoints
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups: [batch]
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups: [apps]
    resources:
      - daemonsets
      - replicasets
      - statefulsets
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups: [policy]
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups: [admissionregistration.k8s.io]
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:vpa-status-actuator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:vpa-status-actuator
subjects:
  - kind: ServiceAccount
    name: vpa-recommender
    namespace: scheduling
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:vpa-checkpoints-reader
rules:
  - apiGroups: [autoscaling.k8s.io]
    resources:
      - verticalpodautoscalercheckpoints
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:vpa-checkpoints-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:vpa-checkpoints-reader
subjects:
  - kind: ServiceAccount
    name: vpa-recommender
    namespace: scheduling
